modLoader="javafml" #mandatory

loaderVersion="[34,)" #mandatory (35 is current forge version)

credits="Thanks to Udemy for great Java courses." #optional

authors="kwpugh" #optional
license="MIT"

[[mods]] #mandatory
modId="powder_power" #mandatory
version="3.2.25" #mandatory
displayName="Powder Power" #mandatory
description='''
Powder alchemy comes to Minecraft
'''


[[dependencies.powder_power]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"


# Here's another dependency
[[dependencies.powder_power]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.16.4]"
    ordering="NONE"
    side="BOTH"
